modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "oneironaut"
version = "${version}"
displayName = "Oneironaut"
logoFile = "icon.png"
authors = "beholderface"
description = '''
Oneironaut addon for Hex Casting
'''

[[dependencies.oneironaut]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oneironaut]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oneironaut]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oneironaut]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.3,)"
ordering = "NONE"
side = "BOTH"

[[mods]]
modId ="hexal"
version = "0.2.18"
displayName = "Hexal"
logoFile = "icon.png"
authors = "talia-12"
description = "uhh hexal I guess"

[[mods]]
modId ="geckolib"
version = "3.1.40"
displayName = "GeckoLib"
logoFile = "icon.png"
authors = "bernie-g"
description = "uhh geckolib I guess"