# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.0.3
_src_path: gh:object-Object/hexdummy
author: beholderface
capitalize_platforms: false
classname: Oneironaut
default_branch: main
description: Oneironaut addon for Hex Casting
display_name: Oneironaut
github_repo: oneironaut
hexcasting_version: 0.10.3
homepage_url: https://beholderface.github.io/oneironaut
initial_mod_version: 0.0.1
java_version: 17
license: MIT
mappings: '"net.fabricmc:yarn:1.19.2+build.28:v2"'
modid: oneironaut
package: net.oneironaut
sources_url: https://github.com/beholderface/oneironaut
