# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.10
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: beholderface
book_id: oneironaut:oneironautbook
default_branch: main
github_repo: oneironaut
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: OneironautModPlugin
hexdoc_plugin_classname: OneironautPlugin
java_lang:
    ext: java
    src: java
java_package: net/oneironaut
mod_display_name: Oneironaut
modid: oneironaut
multiloader: true
package_export_root: doc/src/hexdoc_oneironaut/_export
package_name: hexdoc-oneironaut
package_slug: hexdoc_oneironaut
package_src: doc/src/hexdoc_oneironaut
pages_url: https://beholderface.github.io/oneironaut
pattern_regex:
    per_world_value: registerPerWorld
    regex: (?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?
pattern_registry: registry/OneironautPatternRegistry.java
